name: Run Scavenger Hunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute_scavenger_hunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Checksums
        run: |
          echo "82df43de10e03f70c2a5776a3aad80d3445bfcfb63b79d36706d37b76198c7bc  python/python.test.py.gpg" | sha256sum --check --status
          echo "241f14843342421d8490db6b2850005934bf19b8f2f75d4e8b20847d0ae251f8  ruby/ruby.test.rb.gpg" | sha256sum --check --status
          echo "f3541be6871f9c8487f735ee38ad32be24454df64cc783c37b2fd1cf10d7bacb  tests/testci.sh.gpg" | sha256sum --check --status

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          cd ruby && bundle install && cd ..

      - name: Decrypt tests
        env:
          DECRYPT_SECRET: faf7d3258d56f30b4ce663ea33d6d9c7
        run: |
          if [ -f tests/testci.sh.gpg ]; then
            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d tests/testci.sh.gpg > tests/testci.sh

            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d python/python.test.py.gpg > python/python.test.py
            gpg --batch --yes --passphrase "$DECRYPT_SECRET" -d ruby/ruby.test.rb.gpg > ruby/ruby.test.rb
            echo "All script files decrypted successfully"
          else
            exit 1
          fi

      - name: Run TestCI
        env:
          JWT_SECRET: faf7d3258d56f30b4ce663ea33d6d9c7
          GITHUB_ACTOR: test_actor
        run: |
          chmod +x ./tests/testci.sh
          ./tests/testci.sh
